### ISSUE TITLE
Add deploy-requirements.txt

### ISSUE THREAD

**Issue by conruggles** [rugglcon/python-backgroundchanger#11]
Make the requirements needed for deployment get installed via a new requirements file rather than directly in the pipeline.

**Comment by conruggles** [comment]
@wevnasc

**Comment by wevnasc** [comment]
Hey @rugglcon could you assign this to me? I will do it as soon as my current PRs are merged!

**Comment by conruggles** [comment]
Hey I was rearranging stuff and updating README and whatnot, and ended up doing this myself as I forgot it was even an open issue. Sorry about that! I'm sure there's other things that can be done to improve the project.
