### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by conruggles** [rugglcon/python-backgroundchanger#12]
Tests would be nice to have for the main module code.

Along with this, a CI job to run those tests before a PR can be merged would be added as well.

**Comment by ssghait007** [comment]
I would like to work on this issue, can you assign this to me.

**Comment by vampirepapi** [comment]
i would love to work on this issue,please assign this to me. Thanks!

**Comment by saurabh747** [comment]
cloudinary.uploader.upload("baseball.jpg",
  public_id = "baseball_no_bg",
  background_removal = "cloudinary_ai",

**Comment by conruggles** [comment]
@vampirepapi looks like @ssghait007 is already assigned and working on it.
