### ISSUE TITLE
Figure out an easier way to add the Unsplash API key

### ISSUE THREAD

**Issue by conruggles** [rugglcon/python-backgroundchanger#2]
Right now, it looks for a config file in `~/.config/python-backgroundchanger/unsplash_keys.json`, but it would be nice to not have to add a config file every time, or to create it/prompt to create it when the pypi package is installed.

**Comment by williamhatcher** [comment]
Looks like you need to register for an API key so there's not a way to create a key when the package is installed. Not sure about prompting during installation but the program could prompt on first run if the key isn't present.

https://unsplash.com/developers

**Comment by conruggles** [comment]
That’s a great idea, I think that would be best along with adding a notice in the README that perhaps clarified what needs to be done in order to use this tool.

**Comment by arin17bishwa** [comment]
How about we add a command line argument to give the api key?
If an API key  is given then it will be used and also saved in the config for future uses, otherwise search for the API key in the same manner as now;  so the API key needs to be used only once i.e, during the first run.

That will also mean that the arguments need to be parsed before the creation of the config directories.

**Comment by conruggles** [comment]
Yeah that's a good idea too, would you mind working on that? @arin17bishwa

**Comment by arin17bishwa** [comment]
Yeah sure, I would love to.
Although I must add I have some exams this week, so progress this week might be slow.

**Comment by conruggles** [comment]
No problem, school first of course.

**Comment by raghavddps2** [comment]
Hi @rugglcon ,

Can I take work on this issue ?

**Comment by arin17bishwa** [comment]
@raghavddps2 , if you don't mind.....I have already started working on it actually 😅

**Comment by arin17bishwa** [comment]
@rugglcon ,made a [PR](https://github.com/rugglcon/python-backgroundchanger/pull/22) , please do check it out.
Took a lot less time than I thought.

**Comment by raghavddps2** [comment]
@arin17bishwa Sure, No problem.

**Comment by conruggles** [comment]
This was resolved with #22
