### ISSUE TITLE
Add GitHub Action pipeline to upload package to pypi

### ISSUE THREAD

**Issue by conruggles** [rugglcon/python-backgroundchanger#4]

**Comment by shivamsn97** [comment]
I can do this. Please assign.

Also, add two variables in your secrets:
PYPI_USERNAME = your pypi username
PYPI_PASSWORD = your pypi password

Noone will be able to see your secrets, including me.

**Comment by conruggles** [comment]
Hey @shivamsn97 , @wevnasc I think is already on this, I apologize they weren't assigned to this. You two could split the work if you want, doesn't really matter to me as long as it gets done. the discussion took place in the linked issue above. Whatever is decided, please let me know so I can assign the correct person. Thanks!

**Comment by shivamsn97** [comment]
Oops, i already have opened a PR (#6 ) for the same. 
Its up to you if you want to merge or not.

**Comment by wevnasc** [comment]
Don't worries I haven't started.
